In [1]:
import numpy as np

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
type(iris)

sklearn.utils._bunch.Bunch

In [7]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [11]:
X = iris.data

In [12]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [13]:
y = iris.target

In [14]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [20]:
# One hot encoding 

In [16]:
from keras.utils import to_categorical

In [17]:
y = to_categorical(y)

In [18]:
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [19]:
y.shape

(150, 3)

### Split the data into train and test

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [26]:
X_train

array([[5.7, 2.9, 4.2, 1.3],
       [7.6, 3. , 6.6, 2.1],
       [5.6, 3. , 4.5, 1.5],
       [5.1, 3.5, 1.4, 0.2],
       [7.7, 2.8, 6.7, 2. ],
       [5.8, 2.7, 4.1, 1. ],
       [5.2, 3.4, 1.4, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [5.1, 3.8, 1.9, 0.4],
       [5. , 2. , 3.5, 1. ],
       [6.3, 2.7, 4.9, 1.8],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [5.6, 2.7, 4.2, 1.3],
       [5.1, 3.4, 1.5, 0.2],
       [5.7, 3. , 4.2, 1.2],
       [7.7, 3.8, 6.7, 2.2],
       [4.6, 3.2, 1.4, 0.2],
       [6.2, 2.9, 4.3, 1.3],
       [5.7, 2.5, 5. , 2. ],
       [5.5, 4.2, 1.4, 0.2],
       [6. , 3. , 4.8, 1.8],
       [5.8, 2.7, 5.1, 1.9],
       [6. , 2.2, 4. , 1. ],
       [5.4, 3. , 4.5, 1.5],
       [6.2, 3.4, 5.4, 2.3],
       [5.5, 2.3, 4. , 1.3],
       [5.4, 3.9, 1.7, 0.4],
       [5. , 2.3, 3.3, 1. ],
       [6.4, 2.7, 5.3, 1.9],
       [5. , 3.3, 1.4, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 2.4, 3.8, 1.1],
       [6.7, 3

In [25]:
X_test

array([[6.1, 2.8, 4.7, 1.2],
       [5.7, 3.8, 1.7, 0.3],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.9, 4.5, 1.5],
       [6.8, 2.8, 4.8, 1.4],
       [5.4, 3.4, 1.5, 0.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.9, 3.1, 5.1, 2.3],
       [6.2, 2.2, 4.5, 1.5],
       [5.8, 2.7, 3.9, 1.2],
       [6.5, 3.2, 5.1, 2. ],
       [4.8, 3. , 1.4, 0.1],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.1, 3.8, 1.5, 0.3],
       [6.3, 3.3, 4.7, 1.6],
       [6.5, 3. , 5.8, 2.2],
       [5.6, 2.5, 3.9, 1.1],
       [5.7, 2.8, 4.5, 1.3],
       [6.4, 2.8, 5.6, 2.2],
       [4.7, 3.2, 1.6, 0.2],
       [6.1, 3. , 4.9, 1.8],
       [5. , 3.4, 1.6, 0.4],
       [6.4, 2.8, 5.6, 2.1],
       [7.9, 3.8, 6.4, 2. ],
       [6.7, 3. , 5.2, 2.3],
       [6.7, 2.5, 5.8, 1.8],
       [6.8, 3.2, 5.9, 2.3],
       [4.8, 3. , 1.4, 0.3],
       [4.8, 3.1, 1.6, 0.2],
       [4.6, 3.6, 1. , 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [6.7, 3.1, 4.4, 1.4],
       [4.8, 3.4, 1.6, 0.2],
       [4.4, 3

In [27]:
y_train

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0

In [28]:
y_test

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0

### Standardizing the data

In [30]:
from sklearn.preprocessing import MinMaxScaler

In [54]:
scaler_object = MinMaxScaler()

In [55]:
scaler_object.fit(X_train)

MinMaxScaler()

In [56]:
scaled_X_train = scaler_object.transform(X_train)

In [57]:
scaled_X_test = scaler_object.transform(X_test)

In [58]:
X_train.max()

7.7

In [59]:
scaled_X_train.max()

1.0

In [60]:
X_test.max()

7.9

In [61]:
scaled_X_test.max()

1.0909090909090908

### Model

In [62]:
from keras.models import Sequential
from keras.layers import Dense

In [63]:
model = Sequential()

In [64]:
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [65]:
model.fit(scaled_X_train,y_train, epochs=150, verbose=2)

Epoch 1/150
4/4 - 1s - loss: 1.0940 - accuracy: 0.3500 - 609ms/epoch - 152ms/step
Epoch 2/150
4/4 - 0s - loss: 1.0865 - accuracy: 0.3500 - 15ms/epoch - 4ms/step
Epoch 3/150
4/4 - 0s - loss: 1.0791 - accuracy: 0.3500 - 9ms/epoch - 2ms/step
Epoch 4/150
4/4 - 0s - loss: 1.0714 - accuracy: 0.3500 - 8ms/epoch - 2ms/step
Epoch 5/150
4/4 - 0s - loss: 1.0626 - accuracy: 0.3500 - 10ms/epoch - 2ms/step
Epoch 6/150
4/4 - 0s - loss: 1.0542 - accuracy: 0.3500 - 12ms/epoch - 3ms/step
Epoch 7/150
4/4 - 0s - loss: 1.0461 - accuracy: 0.3500 - 11ms/epoch - 3ms/step
Epoch 8/150
4/4 - 0s - loss: 1.0358 - accuracy: 0.3500 - 10ms/epoch - 2ms/step
Epoch 9/150
4/4 - 0s - loss: 1.0264 - accuracy: 0.3300 - 13ms/epoch - 3ms/step
Epoch 10/150
4/4 - 0s - loss: 1.0175 - accuracy: 0.3300 - 12ms/epoch - 3ms/step
Epoch 11/150
4/4 - 0s - loss: 1.0088 - accuracy: 0.3300 - 13ms/epoch - 3ms/step
Epoch 12/150
4/4 - 0s - loss: 1.0000 - accuracy: 0.3200 - 10ms/epoch - 2ms/step
Epoch 13/150
4/4 - 0s - loss: 0.9920 - accuracy:

In [66]:
model.predict(scaled_X_test)

2/2 [==============================] - 0s 4ms/step


array([[3.7337776e-02, 6.4776599e-01, 3.1489626e-01],
       [9.2232847e-01, 7.5812779e-02, 1.8587328e-03],
       [6.5921493e-05, 7.6797903e-02, 9.2313623e-01],
       [2.5301296e-02, 5.7796013e-01, 3.9673859e-01],
       [1.2792593e-02, 5.3655183e-01, 4.5065558e-01],
       [8.8882852e-01, 1.0708155e-01, 4.0898803e-03],
       [1.1037192e-01, 6.7922252e-01, 2.1040559e-01],
       [9.3985972e-04, 2.1203138e-01, 7.8702879e-01],
       [4.0204730e-03, 2.8499505e-01, 7.1098441e-01],
       [6.9654010e-02, 6.6275638e-01, 2.6758966e-01],
       [4.6183839e-03, 3.8631657e-01, 6.0906506e-01],
       [9.0122843e-01, 9.4061680e-02, 4.7099353e-03],
       [9.2044723e-01, 7.7059947e-02, 2.4928628e-03],
       [9.0692657e-01, 8.9045964e-02, 4.0274146e-03],
       [9.3734187e-01, 6.1227847e-02, 1.4302785e-03],
       [3.0876579e-02, 6.6143799e-01, 3.0768546e-01],
       [6.3662132e-04, 1.7513730e-01, 8.2422608e-01],
       [6.8876058e-02, 6.4032036e-01, 2.9080355e-01],
       [4.2670574e-02, 6.288

### Evaluating model performance

In [67]:
model.metrics_names

['loss', 'accuracy']

In [69]:
model.evaluate(x=scaled_X_test, y = y_test)

2/2 [==============================] - 0s 4ms/step - loss: 0.2823 - accuracy: 0.9800


[0.28228169679641724, 0.9800000190734863]

In [70]:
from sklearn.metrics import confusion_matrix, classification_report

In [71]:
predictions = model.predict(scaled_X_test)

2/2 [==============================] - 0s 2ms/step


In [72]:
predictions

array([[3.7337776e-02, 6.4776599e-01, 3.1489626e-01],
       [9.2232847e-01, 7.5812779e-02, 1.8587328e-03],
       [6.5921493e-05, 7.6797903e-02, 9.2313623e-01],
       [2.5301296e-02, 5.7796013e-01, 3.9673859e-01],
       [1.2792593e-02, 5.3655183e-01, 4.5065558e-01],
       [8.8882852e-01, 1.0708155e-01, 4.0898803e-03],
       [1.1037192e-01, 6.7922252e-01, 2.1040559e-01],
       [9.3985972e-04, 2.1203138e-01, 7.8702879e-01],
       [4.0204730e-03, 2.8499505e-01, 7.1098441e-01],
       [6.9654010e-02, 6.6275638e-01, 2.6758966e-01],
       [4.6183839e-03, 3.8631657e-01, 6.0906506e-01],
       [9.0122843e-01, 9.4061680e-02, 4.7099353e-03],
       [9.2044723e-01, 7.7059947e-02, 2.4928628e-03],
       [9.0692657e-01, 8.9045964e-02, 4.0274146e-03],
       [9.3734187e-01, 6.1227847e-02, 1.4302785e-03],
       [3.0876579e-02, 6.6143799e-01, 3.0768546e-01],
       [6.3662132e-04, 1.7513730e-01, 8.2422608e-01],
       [6.8876058e-02, 6.4032036e-01, 2.9080355e-01],
       [4.2670574e-02, 6.288

In [73]:
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)